<?php

if ( !function_exists( 'shoestrap_compiler' ) ) :
/*
 * This function can be used to compile a less file to css using the lessphp compiler
 */
function shoestrap_compiler() {
  $minimize_css = shoestrap_getVariable( 'minimize_css', true );
  $options = ( $minimize_css == 1 ) ? array( 'compress'=>true ) : array( 'compress'=>false );

  $bootstrap_location = get_template_directory() . '/assets/less/';
  $webfont_location   = get_template_directory() . '/assets/fonts/';
  $bootstrap_uri      = '';

  try {

    $parser = new Less_Parser( $options );

    // The main app.less file
    $parser->parseFile( $bootstrap_location . 'app.less', $bootstrap_uri );
    // Our custom variables
    $parser->parse( shoestrap_variables() );

    // Include the Elusive Icons
    $parser->parseFile( $webfont_location . 'elusive-webfont.less', $bootstrap_uri );

    // Enable gradients
    if ( shoestrap_getVariable( 'gradients_toggle' ) == 1 )
      $parser->parseFile( $bootstrap_location . 'gradients.less', $bootstrap_uri );
      
    // Parse any custom less added by the user
    $parser->parse( shoestrap_getVariable( 'user_less' ) );
    // Add a filter to the compiler
    $parser->parse( apply_filters( 'shoestrap_compiler', '' ) );

    $css = $parser->getCss();

  } catch( Exception $e ) {
    $error_message = $e->getMessage();
    error_log($error_message);    
  }

  // Below is just an ugly hack
  $css = str_replace( 'bootstrap/fonts/', '', $css );
  $css = str_replace( get_template_directory_uri() . '/assets/', '../', $css );
  return apply_filters( 'shoestrap_compiler_output', $css );
}
endif;

// Alleycat less compiler
function alleycat_compiler() {
  $minimize_css = shoestrap_getVariable( 'minimize_css', true );
  $options = ( $minimize_css == 1 ) ? array( 'compress'=>true ) : array( 'compress'=>false );
  $bootstrap_location = get_template_directory() . '/assets/less/';
  $bootstrap_uri      = '';

  try {

    $parser = new Less_Parser( $options );
      
    // AC LESS file
    $parser->parseFile( $bootstrap_location . 'alleycat.less', $bootstrap_uri );
    
    // Our custom variables
    $parser->parse( shoestrap_variables() );

    // Add a filter to the compiler
    $parser->parse( apply_filters( 'shoestrap_compiler', '' ) );

    $css = $parser->getCss();

  } catch( Exception $e ) {
    $error_message = $e->getMessage();
    error_log($error_message);
  }

  // Below is just an ugly hack
  $css = str_replace( 'bootstrap/fonts/', '', $css );
  $css = str_replace( get_template_directory_uri() . '/assets/', '../', $css );
  return apply_filters( 'shoestrap_compiler_output', $css );
}


if ( !function_exists( 'shoestrap_makecss' ) ) :
function shoestrap_makecss( $method = 'php' ) {

  global $wp_filesystem;
  $file = shoestrap_css();
  
  // Initialize the Wordpress filesystem, no more using file_put_contents function
  if ( empty( $wp_filesystem ) ) {
    require_once( ABSPATH . '/wp-admin/includes/file.php' );
    WP_Filesystem();
  }

  $content = ac_compiler_get_top_message();
  $content .= shoestrap_compiler();

  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) {
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) )
      return apply_filters( 'shoestrap_css_output', $content );
  }
  


  // Now create the Alleycat.css file
  $file = get_template_directory().'/assets/css/alleycat.css';
  $content = ac_compiler_get_top_message();
  $content .= alleycat_compiler();
  
  if ( is_writeable( $file ) || ( !file_exists( $file ) && is_writeable( dirname( $file ) ) ) ) {
    if ( !$wp_filesystem->put_contents( $file, $content, FS_CHMOD_FILE ) )
      return apply_filters( 'shoestrap_css_output', $content );
  }
  
}
endif;

function ac_compiler_get_top_message() {
	return "/********* !!! Do not edit this file !!! *********/
/* This file is automatically generated and any changes you make will be lost */
/* You can change settings in the Theme Options and this file will contain those changes */
/* Write your own CSS in the Custom CSS field in the Theme Options, or use a child theme */

";
}